defaults:
  - global/logs/local/default
  - global/logs/logger/mlflow
  - pipeline/training/dataset: default
  - pipeline/training: default
  - pipeline/training/balancing: default
  - _self_

hydra:
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}